config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'corona', to: 'pages#corona'
  get 'klanten', to: 'pages#klanten'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def corona
  end

   def greet
    if Time.now.between? Time.now.beginning_of_day, Time.now.middle_of_day
      return "Good Morning"
    elsif Time.now.between? Time.now.middle_of_day, Time.now.change(hour: 17)
      return "Good Afternoon"
    elsif Time.now.between? Time.now.change(hour: 17), Time.now.change(hour: 20)
      return "Good Evening"
    elsif Time.now.between? Time.now.change(hour: 20), Time.now.end_of_day
      return "Good Night"
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChristaHospersBg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
      <%= render 'shared/navbar' %>

    <%= yield %>
  </body>
    <%= render 'shared/footer' %>
</html>

app/views/pages/about.html.erb
<div class="about-banner">
  <h1><strong>Christa Hospers</strong></h1>
  <h2><i>bedrijf en gezondheid</i></h2>
</div>

<div class="container">

<div class="card-product mt-4">
 <%= image_tag "foto.jpg" %>
  <div class="card-product-infos">
    <h2>Product name</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo odit quasi recusandae, similique necessitatibus nisi. Ab, accusantium consequuntur amet dolorum aliquid! At nostrum consequuntur obcaecati, libero esse, perspiciatis sapiente vero!</p>
  </div>
</div>

</div>

app/views/pages/contact.html.erb
<div class="home-banner">
  <h1><strong>Christa Hospers</strong></h1>
  <h2><i>bedrijf en gezondheid</i></h2>
</div>

<div class="container">

<h1>Contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/corona.html.erb
<div class="corona-banner">
</div>

<div class="container">

  <div mt-5>
    <h1>Coronavirus en werk: alles wat u moet weten</h1>
    <p>
      Op deze pagina vindt u alle actuele informatie over het coronavirus in relatie tot werk en hoe uw organisatie hiermee kan omgaan. De richtlijnen en informatie van het RIVM en de overige betrouwbare bronnen zijn leidend. Aanvullend daarop biedt het werkgeversadvies u hulp gericht op de werksituatie.

      Let op: Naar aanleiding van de aangescherpte maatregelen om verdere verspreiding van het coronavirus (COVID-19) af te remmen, voeren wij het spreekuur van de bedrijfsarts op dit moment zoveel mogelijk telefonisch. Is het spreekuur van uw medewerker al gepland als een fysiek bezoek, dan nemen we hiervoor contact met de medewerker op om dit om te zetten in een telefonisch consult.
    </p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-banner">
</div>

<div class="container">
  <div class="col-6 offset-3 mt-3">


    <h1>Christa Hospers</h1>
    <h2><i>Bedrijf en gezondheid</i></h2>
    <p><i><%= "#{@greet}"%></i></p>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempore, modi minus rem enim, perspiciatis fugit animi expedita hic aspernatur ipsum ratione, cum. Tempora animi, aut voluptatibus odit eligendi assumenda inventore.</p>
  </div>
</div>

app/views/pages/klanten.html.erb
<div class="home-banner">
  <h1><strong>Christa Hospers</strong></h1>
  <h2><i>bedrijf en gezondheid</i></h2>
</div>

<div class="container">

<h1>Klanten</h1>
<p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/shared/_footer.html.erb
<div class="container-footer">
<div class="footer">
 <ul class="list">
  <li><a href="https://www.facebook.com/isabelle.rousseau.566" target="_blank"><i class="fab fa-facebook"></i></a></li>
  <li><a href="https://www.instagram.com/isabellerousseau/?hl=nl" target="_blank"><i class="fab fa-instagram"></i></a></li>
  <li><a href="https://www.linkedin.com/in/christa-hospers-62563315/" target="_blank"><i class="fab fa-linkedin"></i></a></li>
</ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">
   <%= image_tag "logo.png" %>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
        <div class="dropdown-menu dropdown-menu-right alwaysontop" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#"><%= link_to "Home", root_path, class: "nav-link" %></a>
          <a class="dropdown-item" href="#"><%= link_to "Over mij", about_path, class: "nav-link" %></a>
          <a class="dropdown-item" href="#"><%= link_to "Klanten", klanten_path, class: "nav-link" %></a>
          <a class="dropdown-item" href="#"><%= link_to "Contact", contact_path, class: "nav-link" %></a>
          <a class="dropdown-item" href="#"><%= link_to "Corona", corona_path, class: "nav-link" %></a>
        </div>
      </li>
    </ul>
  </div>
</div>